// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfnaopgzaeewhvhhvxbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mbmFvcGd6YWVld2h2aGh2eGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTI5NTksImV4cCI6MjA2MjEyODk1OX0.iDMZvfccrvO_wbtgPPf_RjVlyKV401kM8cNppNBoG14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);